-- One-time Snowflake setup. Run manually via Snowflake UI or SnowSQL.
-- This creates the database, schemas, and warehouse for the project.

CREATE DATABASE IF NOT EXISTS BASEBALL_ANALYTICS;

USE DATABASE BASEBALL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;

CREATE WAREHOUSE IF NOT EXISTS BASEBALL_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
